# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache ./work/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir ./work/wt [current_project]
#set_property parent.project_path ../fpga/mpz7020.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo ./work/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  testbench.text.mem
  testbench.data.mem
}
read_verilog -library xil_defaultlib -sv {
  ../src/main/sv/amba/apb.sv
  ../src/main/sv/timer/apb_timer.sv
  ../src/main/sv/uart/apb_uart.sv
  ../src/main/sv/amba/axi4.sv
  ../src/main/sv/amba/axi.sv
  ../src/main/sv/amba/axi2apb.sv
  ../src/main/sv/ram/blockram.sv
  ../src/main/sv/uart/io_generic_fifo.sv
  ../src/main/sv/ram/ram.sv
  ../src/main/sv/timer/timer.sv
  ../src/main/sv/uart/uart_interrupt.sv
  ../src/main/sv/uart/uart_rx.sv
  ../src/main/sv/uart/uart_tx.sv
  ../src/main/sv/soc/soc.sv
}
read_verilog -library xil_defaultlib ./Cpu.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc ../fpga/board.xdc
set_property used_in_implementation true [get_files ../fpga/board.xdc]

set_param ips.enableIPCacheLiteLoad 1

synth_design -top soc -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_utilization_synth.rpt -pb soc_utilization_synth.pb"
